namespace: joellefkowitz
name: swarmroles-support
description: Add on roles for deploying a docker swarm
version: 0.1.0

readme: README.md
authors:
  - Joel Lefkowitz <joellefkowitz@hotmail.com>

license:
  - MIT

tags: []
dependencies: {}

repository: &repo https://github.com/JoelLefkowitz/swarmroles-support
issues: https://github.com/JoelLefkowitz/swarmroles-support/issues

homepage: *repo
documentation: *repo

build_ignore: [venv]
