namespace: joellefkowitz
name: swarmroles
description: Roles for deploying a docker swarm
version: 1.4.1

readme: README.md
authors:
  - Joel Lefkowitz <joellefkowitz@hotmail.com>

license:
  - MIT

tags: []
dependencies: {}

repository: &repo https://github.com/s3pweb/swarmroles
issues: https://github.com/JoelLefkowitz/swarmroles/issues

homepage: *repo
documentation: *repo

build_ignore: [venv]
